---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  destination:
    namespace: qa
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: git@github.com:caju-org/gitops-studies
      path: charts/hello-app
      targetRevision: main
      helm:
        releaseName: hello-app
        valueFiles:
          - $values/qa/hello-app/values.yaml
    - repoURL: 'https://github.com/caju-org/gitops-value-files.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
