apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  destination:
    namespace: qa
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/hello-app
    repoURL: git@github.com:caju-org/gitops-studies
    targetRevision: main
    helm:
      releaseName: hello-app
      values: |
        image:
          repository: "gcr.io/google-samples/hello-app"
          tag: "1.0"
        service:
          port: 8080
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: hello-app.caju.local
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      port:
                        number: 8080
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
